= Honeycomb {project-version} Release notes

Release notes for honeycomb {project-version}.

Honeycomb is a generic NETCONF/RESTCONF management agent and provides a framework
for building specialized agents.

It uses many features and utilities from different http://www.opendaylight.org/[Opendaylight (ODL)] projects
(e.g. yangtools, controller, mdsal and netconf).

The biggest use case of honeycomb is VPP (fd.io's Vector packet processor).
Honeycomb delivers a management agent to enable integration of VPP with e.g. SDN controllers such as Opendaylight.

For VPP specific distribution of Honeycomb, please refer to https://wiki.fd.io/view/Hc2vpp[hc2vpp] project.

== Release plan
https://wiki.fd.io/view/Honeycomb/Release_Plans/Release_Plan_{project-public-version}[Release plan]

== Features
* Generic, model-driven agent framework providing northbound interfaces
** NETCONF
** RESTCONF
* Persistence/reconciliation mechanism
* https://jira.fd.io/browse/HONEYCOMB-18 [Minimal distribution]
** optimized set of ODL components, static wiring, runnable shell scripts

=== New features
* https://jira.fd.io/browse/HONEYCOMB-151[RPC support]
** RPC translation is done using RpcServices registered in RpcRegistry.
* https://jira.fd.io/browse/HONEYCOMB-266[Loading test data from resource files]
** Provides convenient framework for testing translation layer.

=== Removed features

=== Modified features
* https://jira.fd.io/browse/HONEYCOMB-73[Initializers tie-in with readers]
** Instead of root level initializer, initialization can be split among multiple initializing readers
* https://jira.fd.io/browse/HONEYCOMB-270[Readers/ReadCustomizers able to influence presence of resulting data]
** Suitable for presence container readers

=== Deprecated features

== Backlog

Process of spiting honeycomb project into generic (honeycomb) and vpp related (hc2vpp) parts
was done during 1.17.01 release. Issues for both projects were tracked in the same jira.

* https://jira.fd.io/projects/HONEYCOMB/versions/{project-version-in-jira}[JIRA]
* https://jira.fd.io/jira/secure/ReleaseNote.jspa?projectId=10001&version={project-version-in-jira}[Release notes]

include::user_guide/user_guide.adoc[]

include::devel_guide/devel_guide.adoc[]