= Honeycomb {project-version} Release notes

Release notes for honeycomb {project-version}.

Honeycomb is a generic NETCONF/RESTCONF management agent and provides a framework
for building specialized agents.

The biggest use case of honeycomb is VPP (fd.io's Vector packet processor).
Honeycomb delivers a management agent to enable integration of VPP with e.g. SDN controllers such as Opendaylight.

For VPP specific distribution of Honeycomb, refer to:
!!!!! FIXME/TODO add link !!!!!!

== Release plan
https://wiki.fd.io/view/Honeycomb/Release_Plans/Release_Plan_{project-public-version}[Release plan]

== Features
Adding to the list of existing features: https://wiki.fd.io/view/Honeycomb/Releases/1609#Features[1609 feature list]:

=== New features

=== Removed features

=== Modified features
* https://jira.fd.io/browse/HONEYCOMB-73[Initializers tie-in with readers]
** Instead of root level initializer, initialization can be split among multiple initializing readers
* https://jira.fd.io/browse/HONEYCOMB-270[Readers/ReadCustomizers able to influence presence of resulting data]
** Suitable for presence container readers

=== Deprecated features

== Backlog

* https://jira.fd.io/projects/HONEYCOMB/versions/{project-version-in-jira}[JIRA]
* https://jira.fd.io/jira/secure/ReleaseNote.jspa?projectId=10001&version={project-version-in-jira}[Release notes]

include::user_guide/user_guide.adoc[]

include::devel_guide/devel_guide.adoc[]